import { Archive, Check, ChevronDown, Edit3, Hash, Plus, Trash2, UserPlus, X } from 'lucide-react-native';
import { useCallback, useEffect, useState } from 'react';
import { Alert, Modal, Pressable, RefreshControl, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { Avatar } from '@/components/avatar';
import { ErrorState, LoadingState } from '@/components/screen-states';
import { fonts, palette } from '@/constants/csg-theme';
import type { ChannelSummary, UserSummary, WorkspaceDetail } from '@/lib/types';
import { useSession } from '@/providers/session-provider';
import { useWorkspace } from '@/providers/workspace-provider';

type Editor = 'workspace' | 'channel' | 'members' | null;

export default function ManageCommunicationsScreen() {
  const { api, user } = useSession();
  const { workspaces, activeWorkspaceId, activeWorkspace, selectWorkspace, refresh: refreshWorkspaces } = useWorkspace();
  const [workspace, setWorkspace] = useState<WorkspaceDetail | null>(null);
  const [channels, setChannels] = useState<ChannelSummary[]>([]);
  const [users, setUsers] = useState<UserSummary[]>([]);
  const [editor, setEditor] = useState<Editor>(null);
  const [editingChannel, setEditingChannel] = useState<ChannelSummary | null>(null);
  const [editingWorkspace, setEditingWorkspace] = useState<WorkspaceDetail | null>(null);
  const [showWorkspacePicker, setShowWorkspacePicker] = useState(false);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async (pull = false) => {
    if (!user?.is_staff || !activeWorkspaceId) { setLoading(false); return; }
    if (pull) setRefreshing(true); else setLoading(true);
    try {
      const [workspaceResult, channelResult, userResult] = await Promise.all([api.workspace(activeWorkspaceId), api.channels(), api.users()]);
      setWorkspace(workspaceResult.workspace);
      setChannels(channelResult.channels.filter((channel) => channel.workspace_id === activeWorkspaceId));
      setUsers(userResult.users);
      setError(null);
    } catch (requestError) { setError((requestError as Error).message); }
    finally { setLoading(false); setRefreshing(false); }
  }, [activeWorkspaceId, api, user]);
  useEffect(() => { const frame = requestAnimationFrame(() => void load()); return () => cancelAnimationFrame(frame); }, [load]);

  if (!user?.is_staff) return <SafeAreaView style={styles.safe}><ErrorState message="Staff access is required to manage communications." retry={() => undefined} /></SafeAreaView>;

  const archiveChannel = (channel: ChannelSummary) => Alert.alert(`Archive #${channel.name}?`, 'Existing messages remain available to staff, but members can no longer post.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Archive', style: 'destructive', onPress: async () => { try { await api.archiveChannel(channel.id); setChannels((current) => current.filter((item) => item.id !== channel.id)); } catch (requestError) { Alert.alert('Could not archive channel', (requestError as Error).message); } } }]);
  const removeMember = (member: WorkspaceDetail['members'][number]) => { if (!workspace?.can_manage) return; Alert.alert(`Remove ${member.full_name}?`, `They will lose access to ${workspace.name}.`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: async () => { try { const result = await api.removeWorkspaceMember(workspace.id, member.id); setWorkspace(result.workspace); await refreshWorkspaces(); } catch (requestError) { Alert.alert('Could not remove member', (requestError as Error).message); } } }]); };

  return <SafeAreaView edges={['bottom']} style={styles.safe}>
    <View style={styles.hero}><Text style={styles.eyebrow}>STAFF CONTROLS</Text><Text style={styles.heading}>Communication settings</Text><Text style={styles.subhead}>Changes here immediately affect the same workspaces on web and mobile.</Text></View>
    <Pressable accessibilityRole="button" accessibilityLabel="Switch workspace" onPress={() => setShowWorkspacePicker(true)} style={styles.workspaceSelector}><View style={styles.workspaceMark}><Text style={styles.workspaceInitials}>{initials(activeWorkspace?.name || '')}</Text></View><View style={styles.workspaceCopy}><Text style={styles.workspaceName}>{activeWorkspace?.name || 'Choose a workspace'}</Text><Text style={styles.workspaceMeta}>{activeWorkspace?.workspace_type} · {workspace?.member_count || activeWorkspace?.member_count || 0} members</Text></View><ChevronDown color={palette.muted} size={18} /></Pressable>
    <View style={styles.topActions}><Pressable accessibilityRole="button" onPress={() => { setEditingWorkspace(null); setEditor('workspace'); }} style={styles.secondaryAction}><Plus color={palette.text} size={17} /><Text style={styles.secondaryText}>New community</Text></Pressable><Pressable accessibilityRole="button" disabled={!activeWorkspaceId} onPress={() => { setEditingChannel(null); setEditor('channel'); }} style={styles.primaryAction}><Hash color={palette.text} size={17} /><Text style={styles.primaryText}>New channel</Text></Pressable></View>
    {loading ? <LoadingState /> : error ? <ErrorState message={error} retry={() => void load()} /> : <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={palette.rubySoft} />} contentContainerStyle={styles.content}>
      <View style={styles.sectionHeader}><Text style={styles.sectionLabel}>CHANNELS</Text><Text style={styles.sectionCount}>{channels.length}</Text></View>
      <View style={styles.group}>{channels.map((channel, index) => <Pressable key={channel.id} accessibilityRole="button" accessibilityLabel={`Edit ${channel.name}`} onPress={() => { setEditingChannel(channel); setEditor('channel'); }} onLongPress={() => archiveChannel(channel)} style={[styles.row, index > 0 && styles.rowBorder]}><View style={styles.channelIcon}><Hash color={palette.rubySoft} size={17} /></View><View style={styles.rowCopy}><Text style={styles.rowTitle}>{channel.name}</Text><Text numberOfLines={1} style={styles.rowSubtitle}>{channel.description || `${channel.visibility === 'staff_only' ? 'Staff only' : 'All workspace members'} can view`}</Text></View>{channel.visibility === 'staff_only' && <Text style={styles.staffPill}>STAFF</Text>}<Edit3 color={palette.quiet} size={16} /></Pressable>)}</View>
      <View style={styles.sectionHeader}><Text style={styles.sectionLabel}>MEMBERS</Text><Text style={styles.sectionCount}>{workspace?.members.length || 0}</Text>{workspace?.can_manage && <Pressable accessibilityRole="button" onPress={() => setEditor('members')} style={styles.addMembers}><UserPlus color={palette.rubySoft} size={15} /><Text style={styles.addMembersText}>Add</Text></Pressable>}</View>
      <View style={styles.group}>{workspace?.members.map((member, index) => <View key={member.id} style={[styles.memberRow, index > 0 && styles.rowBorder]}><Avatar name={member.full_name} size={36} /><View style={styles.rowCopy}><Text style={styles.rowTitle}>{member.full_name}</Text><Text style={styles.rowSubtitle}>{member.email}</Text></View><Text style={styles.memberRole}>{member.membership_role}</Text>{workspace.can_manage && member.id !== user.id && <Pressable accessibilityRole="button" accessibilityLabel={`Remove ${member.full_name}`} onPress={() => removeMember(member)} style={styles.removeMember}><Trash2 color={palette.quiet} size={16} /></Pressable>}</View>)}</View>
      {workspace?.can_manage && <Pressable accessibilityRole="button" onPress={() => { setEditingWorkspace(workspace); setEditor('workspace'); }} style={styles.editWorkspace}><Edit3 color={palette.muted} size={17} /><Text style={styles.editWorkspaceText}>Edit this community workspace</Text></Pressable>}
    </ScrollView>}

    <Modal visible={showWorkspacePicker} transparent animationType="slide" onRequestClose={() => setShowWorkspacePicker(false)}><View style={styles.modalRoot}><Pressable style={StyleSheet.absoluteFill} onPress={() => setShowWorkspacePicker(false)} /><View style={styles.sheet}><View style={styles.handle} /><Text style={styles.sheetTitle}>Choose workspace</Text><ScrollView contentContainerStyle={styles.pickerList}>{workspaces.map((item) => <Pressable key={item.id} accessibilityRole="button" onPress={() => { void selectWorkspace(item.id); setShowWorkspacePicker(false); }} style={[styles.pickerRow, item.id === activeWorkspaceId && styles.pickerActive]}><View style={styles.workspaceMark}><Text style={styles.workspaceInitials}>{initials(item.name)}</Text></View><View style={styles.workspaceCopy}><Text style={styles.workspaceName}>{item.name}</Text><Text style={styles.workspaceMeta}>{item.workspace_type} · {item.member_count} members</Text></View>{item.id === activeWorkspaceId && <Check color={palette.rubySoft} size={18} />}</Pressable>)}</ScrollView></View></View></Modal>
    <WorkspaceEditor key={`workspace-${editor}-${editingWorkspace?.id || 'new'}`} visible={editor === 'workspace'} initial={editingWorkspace} onClose={() => { setEditor(null); setEditingWorkspace(null); }} onSave={async (data) => { const result = editingWorkspace ? await api.updateWorkspace(editingWorkspace.id, data) : await api.createWorkspace(data); await refreshWorkspaces(); await selectWorkspace(result.workspace.id); setEditor(null); setEditingWorkspace(null); }} />
    <ChannelEditor key={`channel-${editor}-${editingChannel?.id || 'new'}`} visible={editor === 'channel'} workspaceId={activeWorkspaceId} initial={editingChannel} onClose={() => { setEditor(null); setEditingChannel(null); }} onSave={async (data) => { const result = editingChannel ? await api.updateChannel(editingChannel.id, data) : await api.createChannel({ workspace_id: activeWorkspaceId!, ...data }); setChannels((current) => [result.channel, ...current.filter((item) => item.id !== result.channel.id)]); setEditor(null); setEditingChannel(null); }} onArchive={() => editingChannel && archiveChannel(editingChannel)} />
    <MemberPicker key={`members-${editor}-${workspace?.id || 'none'}`} visible={editor === 'members'} users={users.filter((candidate) => !workspace?.members.some((member) => member.id === candidate.id))} onClose={() => setEditor(null)} onAdd={async (ids) => { if (!workspace) return; const result = await api.addWorkspaceMembers(workspace.id, ids); setWorkspace(result.workspace); await refreshWorkspaces(); setEditor(null); }} />
  </SafeAreaView>;
}

function WorkspaceEditor({ visible, initial, onClose, onSave }: { visible: boolean; initial: WorkspaceDetail | null; onClose: () => void; onSave: (data: { name: string; description?: string }) => Promise<void> }) { const [name, setName] = useState(initial?.name || ''); const [description, setDescription] = useState(initial?.description || ''); const [saving, setSaving] = useState(false); return <EditorShell visible={visible} title={initial ? 'Edit workspace' : 'New community'} onClose={onClose}><Text style={styles.fieldLabel}>NAME</Text><TextInput value={name} onChangeText={setName} placeholder="Community name" placeholderTextColor={palette.quiet} style={styles.field} /><Text style={styles.fieldLabel}>DESCRIPTION</Text><TextInput value={description} onChangeText={setDescription} placeholder="What is this space for?" placeholderTextColor={palette.quiet} multiline style={[styles.field, styles.multiline]} /><Pressable accessibilityRole="button" disabled={!name.trim() || saving} onPress={async () => { setSaving(true); try { await onSave({ name: name.trim(), description: description.trim() }); } catch (requestError) { Alert.alert('Could not save workspace', (requestError as Error).message); } finally { setSaving(false); } }} style={[styles.save, (!name.trim() || saving) && styles.disabled]}><Text style={styles.saveText}>{saving ? 'Saving…' : 'Save workspace'}</Text></Pressable></EditorShell>; }
function ChannelEditor({ visible, workspaceId, initial, onClose, onSave, onArchive }: { visible: boolean; workspaceId: number | null; initial: ChannelSummary | null; onClose: () => void; onSave: (data: { name: string; description?: string; visibility: 'cohort' | 'staff_only' }) => Promise<void>; onArchive: () => void }) { const [name, setName] = useState(initial?.name || ''); const [description, setDescription] = useState(initial?.description || ''); const [staffOnly, setStaffOnly] = useState(initial?.visibility === 'staff_only'); const [saving, setSaving] = useState(false); return <EditorShell visible={visible} title={initial ? `Edit #${initial.name}` : 'New channel'} onClose={onClose}><Text style={styles.fieldLabel}>CHANNEL NAME</Text><TextInput autoCapitalize="none" value={name} onChangeText={(value) => setName(value.toLowerCase().replace(/\s+/g, '-'))} placeholder="help-desk" placeholderTextColor={palette.quiet} style={styles.field} /><Text style={styles.fieldLabel}>DESCRIPTION</Text><TextInput value={description} onChangeText={setDescription} placeholder="What belongs in this channel?" placeholderTextColor={palette.quiet} multiline style={[styles.field, styles.multiline]} /><View style={styles.toggleRow}><View><Text style={styles.toggleTitle}>Staff-only channel</Text><Text style={styles.toggleCopy}>Students will not be able to find or open it.</Text></View><Switch value={staffOnly} onValueChange={setStaffOnly} trackColor={{ false: palette.line, true: '#6A2A36' }} thumbColor={staffOnly ? palette.rubySoft : palette.muted} /></View><Pressable accessibilityRole="button" disabled={!workspaceId || !name.trim() || saving} onPress={async () => { setSaving(true); try { await onSave({ name: name.trim(), description: description.trim(), visibility: staffOnly ? 'staff_only' : 'cohort' }); } catch (requestError) { Alert.alert('Could not save channel', (requestError as Error).message); } finally { setSaving(false); } }} style={[styles.save, (!workspaceId || !name.trim() || saving) && styles.disabled]}><Text style={styles.saveText}>{saving ? 'Saving…' : 'Save channel'}</Text></Pressable>{initial && <Pressable accessibilityRole="button" onPress={() => { onClose(); onArchive(); }} style={styles.archive}><Archive color={palette.rubySoft} size={17} /><Text style={styles.archiveText}>Archive channel</Text></Pressable>}</EditorShell>; }
function MemberPicker({ visible, users, onClose, onAdd }: { visible: boolean; users: UserSummary[]; onClose: () => void; onAdd: (ids: number[]) => Promise<void> }) { const [selected, setSelected] = useState<number[]>([]); const [saving, setSaving] = useState(false); return <EditorShell visible={visible} title="Add members" onClose={onClose}><ScrollView style={styles.memberPicker}>{users.map((member) => { const checked = selected.includes(member.id); return <Pressable key={member.id} accessibilityRole="checkbox" accessibilityState={{ checked }} onPress={() => setSelected((current) => checked ? current.filter((id) => id !== member.id) : [...current, member.id])} style={[styles.pickMember, checked && styles.pickerActive]}><Avatar name={member.full_name} size={36} /><View style={styles.rowCopy}><Text style={styles.rowTitle}>{member.full_name}</Text><Text style={styles.rowSubtitle}>{member.email}</Text></View>{checked && <Check color={palette.rubySoft} size={18} />}</Pressable>; })}</ScrollView><Pressable accessibilityRole="button" disabled={!selected.length || saving} onPress={async () => { setSaving(true); try { await onAdd(selected); } catch (requestError) { Alert.alert('Could not add members', (requestError as Error).message); } finally { setSaving(false); } }} style={[styles.save, (!selected.length || saving) && styles.disabled]}><Text style={styles.saveText}>{saving ? 'Adding…' : `Add ${selected.length || ''} member${selected.length === 1 ? '' : 's'}`}</Text></Pressable></EditorShell>; }
function EditorShell({ visible, title, onClose, children }: { visible: boolean; title: string; onClose: () => void; children: React.ReactNode }) { return <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><SafeAreaView style={styles.editorSafe}><View style={styles.editorHeader}><Text style={styles.editorTitle}>{title}</Text><Pressable accessibilityRole="button" accessibilityLabel="Close" onPress={onClose} style={styles.close}><X color={palette.muted} size={20} /></Pressable></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.editorContent}>{children}</ScrollView></SafeAreaView></Modal>; }
function initials(name: string) { return name.split(/\s+/).map((word) => word[0]).join('').slice(0, 2).toUpperCase(); }

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.ink }, hero: { paddingHorizontal: 20, paddingTop: 18 }, eyebrow: { color: palette.rubySoft, fontFamily: fonts.bold, fontSize: 10, letterSpacing: 1.8 }, heading: { color: palette.text, fontFamily: fonts.extraBold, fontSize: 28, letterSpacing: -0.8, marginTop: 2 }, subhead: { color: palette.muted, fontFamily: fonts.regular, fontSize: 12, lineHeight: 18, marginTop: 5 }, workspaceSelector: { margin: 20, marginBottom: 10, minHeight: 66, padding: 10, borderRadius: 18, backgroundColor: palette.panel, borderWidth: 1, borderColor: palette.line, flexDirection: 'row', alignItems: 'center', gap: 11 }, workspaceMark: { width: 42, height: 42, borderRadius: 13, backgroundColor: '#2A151B', alignItems: 'center', justifyContent: 'center' }, workspaceInitials: { color: palette.text, fontFamily: fonts.bold, fontSize: 12 }, workspaceCopy: { flex: 1 }, workspaceName: { color: palette.text, fontFamily: fonts.bold, fontSize: 14 }, workspaceMeta: { color: palette.quiet, fontFamily: fonts.regular, fontSize: 10, textTransform: 'capitalize', marginTop: 3 },
  topActions: { flexDirection: 'row', gap: 9, paddingHorizontal: 20, paddingBottom: 12 }, secondaryAction: { flex: 1, minHeight: 46, borderRadius: 14, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.panel, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, primaryAction: { flex: 1, minHeight: 46, borderRadius: 14, backgroundColor: palette.ruby, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, secondaryText: { color: palette.text, fontFamily: fonts.bold, fontSize: 11 }, primaryText: { color: palette.text, fontFamily: fonts.bold, fontSize: 11 }, content: { paddingHorizontal: 20, paddingBottom: 40 }, sectionHeader: { minHeight: 45, flexDirection: 'row', alignItems: 'center', gap: 7 }, sectionLabel: { color: palette.quiet, fontFamily: fonts.bold, fontSize: 9, letterSpacing: 1.4 }, sectionCount: { color: palette.rubySoft, fontFamily: fonts.bold, fontSize: 9 }, addMembers: { minHeight: 42, marginLeft: 'auto', flexDirection: 'row', alignItems: 'center', gap: 5 }, addMembersText: { color: palette.rubySoft, fontFamily: fonts.bold, fontSize: 10 }, group: { borderRadius: 20, backgroundColor: palette.panel, borderWidth: 1, borderColor: palette.line, overflow: 'hidden' }, row: { minHeight: 70, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 11 }, rowBorder: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: palette.line }, channelIcon: { width: 38, height: 38, borderRadius: 13, backgroundColor: '#2A151B', alignItems: 'center', justifyContent: 'center' }, rowCopy: { flex: 1, minWidth: 0 }, rowTitle: { color: palette.text, fontFamily: fonts.semibold, fontSize: 13 }, rowSubtitle: { color: palette.quiet, fontFamily: fonts.regular, fontSize: 10, marginTop: 3 }, staffPill: { color: palette.rubySoft, backgroundColor: '#2A151B', borderRadius: 8, overflow: 'hidden', paddingHorizontal: 7, paddingVertical: 4, fontFamily: fonts.bold, fontSize: 7 }, memberRow: { minHeight: 68, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 10 }, memberRole: { color: palette.quiet, fontFamily: fonts.bold, fontSize: 8, textTransform: 'uppercase' }, removeMember: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' }, editWorkspace: { minHeight: 48, marginTop: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, editWorkspaceText: { color: palette.muted, fontFamily: fonts.bold, fontSize: 11 },
  modalRoot: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(2,4,8,0.76)' }, sheet: { maxHeight: '78%', borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: palette.panel, borderWidth: 1, borderColor: palette.line, paddingBottom: 24 }, handle: { width: 38, height: 4, borderRadius: 2, backgroundColor: palette.line, alignSelf: 'center', marginTop: 10 }, sheetTitle: { color: palette.text, fontFamily: fonts.bold, fontSize: 20, margin: 20, marginBottom: 12 }, pickerList: { paddingHorizontal: 16, gap: 8 }, pickerRow: { minHeight: 66, padding: 10, borderRadius: 17, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.panelRaised, flexDirection: 'row', alignItems: 'center', gap: 11 }, pickerActive: { borderColor: '#6A2A36', backgroundColor: '#201319' },
  editorSafe: { flex: 1, backgroundColor: palette.ink }, editorHeader: { minHeight: 64, paddingHorizontal: 20, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.line, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, editorTitle: { color: palette.text, fontFamily: fonts.bold, fontSize: 18 }, close: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, editorContent: { padding: 20, paddingBottom: 50 }, fieldLabel: { color: palette.quiet, fontFamily: fonts.bold, fontSize: 9, letterSpacing: 1.3, marginTop: 16, marginBottom: 7 }, field: { minHeight: 50, borderRadius: 15, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.panel, color: palette.text, fontFamily: fonts.regular, fontSize: 14, paddingHorizontal: 14 }, multiline: { minHeight: 110, paddingTop: 14, textAlignVertical: 'top' }, toggleRow: { minHeight: 74, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12 }, toggleTitle: { color: palette.text, fontFamily: fonts.semibold, fontSize: 13 }, toggleCopy: { color: palette.quiet, fontFamily: fonts.regular, fontSize: 10, marginTop: 3 }, save: { minHeight: 50, borderRadius: 15, backgroundColor: palette.ruby, alignItems: 'center', justifyContent: 'center', marginTop: 24 }, saveText: { color: palette.text, fontFamily: fonts.bold, fontSize: 13 }, disabled: { opacity: 0.4 }, archive: { minHeight: 48, borderRadius: 15, borderWidth: 1, borderColor: '#4A2029', backgroundColor: '#211216', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 10 }, archiveText: { color: palette.rubySoft, fontFamily: fonts.bold, fontSize: 12 }, memberPicker: { maxHeight: 480 }, pickMember: { minHeight: 60, paddingHorizontal: 10, borderRadius: 15, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.panel, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 7 },
});
