import { AlertCircle, Check, ClipboardCheck, Lightbulb, Plus, RotateCcw, Target, Trash2, X } from 'lucide-react-native';
import { useMemo, useState } from 'react';
import { KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { fonts, palette } from '@/constants/csg-theme';
import type { LessonEditorFields, ObjectiveAlignmentField, RetrievalCheckEditorFields } from '@/lib/lesson-editor';
import type { LearningObjective, LessonDetail, Rubric } from '@/lib/types';

type Props = {
  lesson: LessonDetail;
  fields: LessonEditorFields;
  objectives: LearningObjective[];
  rubrics: Rubric[];
  catalogLoading: boolean;
  catalogError: boolean;
  canCreateResources: boolean;
  onRetryCatalogs: () => void;
  onChange: (fields: LessonEditorFields) => void;
  onCreateObjective: (input: { code: string; title: string; description?: string; success_criteria: string }) => Promise<LearningObjective>;
  onCreateRubric: (input: { title: string; description?: string; criteria: { title: string; description: string }[] }) => Promise<Rubric>;
};

export function StaffLearningDesignEditor({ lesson, fields, objectives, rubrics, catalogLoading, catalogError, canCreateResources, onRetryCatalogs, onChange, onCreateObjective, onCreateRubric }: Props) {
  const [objectiveModal, setObjectiveModal] = useState(false);
  const [rubricModal, setRubricModal] = useState(false);
  const selectedObjectiveIds = new Set(fields.objective_alignments.map((alignment) => alignment.learning_objective_id));
  const availableObjectives = objectives.filter((objective) => objective.active && !selectedObjectiveIds.has(objective.id));
  const activeRubrics = rubrics.filter((rubric) => rubric.active !== false);
  const update = (patch: Partial<LessonEditorFields>) => onChange({ ...fields, ...patch });
  const updateCheck = (patch: Partial<RetrievalCheckEditorFields>) => update({ retrieval_check: { ...fields.retrieval_check, ...patch } });

  const addObjective = (objective: LearningObjective) => update({ objective_alignments: [...fields.objective_alignments, { learning_objective_id: objective.id, content_block_id: null }] });
  const removeObjective = (objectiveId: number) => update({ objective_alignments: fields.objective_alignments.filter((alignment) => alignment.learning_objective_id !== objectiveId) });
  const targetObjective = (objectiveId: number, contentBlockId: number | null) => update({ objective_alignments: fields.objective_alignments.map((alignment) => alignment.learning_objective_id === objectiveId ? { ...alignment, content_block_id: contentBlockId } : alignment) });

  return <View style={styles.section}>
    <Text style={styles.eyebrow}>4 · LEARNING DESIGN</Text>
    <Text style={styles.sectionTitle}>Objectives, rubric, and recall</Text>
    <Text style={styles.sectionCopy}>Make the learning target clear, show how work will be reviewed, and add one useful retrieval question.</Text>

    {catalogError && <View style={styles.error}><AlertCircle color={palette.rubySoft} size={18} /><View style={styles.flex}><Text style={styles.errorTitle}>Libraries unavailable</Text><Text style={styles.errorCopy}>Your draft and current selections are safe. Retry to browse the full objective and rubric libraries.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Retry learning design libraries" onPress={onRetryCatalogs} style={styles.retry}><RotateCcw color={palette.rubySoft} size={15} /><Text style={styles.retryText}>Retry</Text></Pressable></View>}

    <DesignCard icon={<Target color={palette.rubySoft} size={19} />} title="Learning objectives" copy="Tell students what they should be able to do when they finish.">
      {catalogLoading && !objectives.length ? <Text style={styles.muted}>Loading objective library…</Text> : <>
        {fields.objective_alignments.map((alignment) => {
          const objective = objectives.find((item) => item.id === alignment.learning_objective_id) || lesson.objectives?.find((item) => item.id === alignment.learning_objective_id);
          if (!objective) return null;
          return <ObjectiveRow key={objective.id} objective={objective} alignment={alignment} lesson={lesson} onTarget={(target) => targetObjective(objective.id, target)} onRemove={() => removeObjective(objective.id)} />;
        })}
        {!fields.objective_alignments.length && <Text style={styles.empty}>No objective attached yet. Choose one from the curriculum library.</Text>}
        {!!availableObjectives.length && <View style={styles.library}><Text style={styles.libraryLabel}>ADD FROM LIBRARY</Text>{availableObjectives.map((objective) => <Pressable key={objective.id} accessibilityRole="button" accessibilityLabel={`Add objective ${objective.code}`} onPress={() => addObjective(objective)} style={styles.libraryChoice}><View style={styles.code}><Text style={styles.codeText}>{objective.code}</Text></View><Text numberOfLines={2} style={styles.libraryChoiceText}>{objective.title}</Text><Plus color={palette.rubySoft} size={17} /></Pressable>)}</View>}
        {canCreateResources && <Pressable accessibilityRole="button" accessibilityLabel="Create learning objective" onPress={() => setObjectiveModal(true)} style={styles.secondary}><Plus color={palette.rubySoft} size={17} /><Text style={styles.secondaryText}>Create a new objective</Text></Pressable>}
      </>}
    </DesignCard>

    <DesignCard icon={<ClipboardCheck color={palette.success} size={19} />} title="Student-visible rubric" copy="Set expectations before students submit their work.">
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>
        <ChoiceChip label="No rubric" selected={fields.rubric_id === null} onPress={() => update({ rubric_id: null })} />
        {activeRubrics.map((rubric) => <ChoiceChip key={rubric.id} label={rubric.title} selected={fields.rubric_id === rubric.id} onPress={() => update({ rubric_id: rubric.id })} />)}
      </ScrollView>
      {fields.rubric_id ? <RubricSummary rubric={rubrics.find((rubric) => rubric.id === fields.rubric_id) || lesson.content_blocks.find((block) => block.rubric?.id === fields.rubric_id)?.rubric} /> : <Text style={styles.empty}>Students will not see grading criteria for this lesson.</Text>}
      {canCreateResources && <Pressable accessibilityRole="button" accessibilityLabel="Create rubric" onPress={() => setRubricModal(true)} style={styles.secondary}><Plus color={palette.rubySoft} size={17} /><Text style={styles.secondaryText}>Create a reusable rubric</Text></Pressable>}
    </DesignCard>

    <DesignCard icon={<Lightbulb color={palette.warning} size={19} />} title="Quick recall check" copy="Use one low-stakes question, then explain the answer immediately.">
      <View style={styles.toggle}><View style={styles.flex}><Text style={styles.toggleTitle}>{fields.retrieval_check.enabled ? 'Included in this lesson' : 'No recall check'}</Text><Text style={styles.toggleCopy}>{fields.retrieval_check.attempt_count ? 'Student attempts lock this question to preserve evidence.' : 'Students can retry after seeing the explanation.'}</Text></View><Switch accessibilityLabel="Include quick recall check" disabled={fields.retrieval_check.attempt_count > 0} value={fields.retrieval_check.enabled} onValueChange={(enabled) => updateCheck({ enabled })} trackColor={{ false: palette.line, true: '#6A2A36' }} thumbColor={fields.retrieval_check.enabled ? palette.rubySoft : palette.muted} /></View>
      {fields.retrieval_check.attempt_count > 0 && <View style={styles.locked}><Check color={palette.warning} size={17} /><Text style={styles.lockedText}>{fields.retrieval_check.attempt_count} student {fields.retrieval_check.attempt_count === 1 ? 'attempt is' : 'attempts are'} recorded. Create a new check if the standard changes.</Text></View>}
      {fields.retrieval_check.enabled && <CheckFields check={fields.retrieval_check} objectives={objectives} locked={fields.retrieval_check.attempt_count > 0} onChange={updateCheck} />}
    </DesignCard>

    <ObjectiveCreateModal visible={objectiveModal} onClose={() => setObjectiveModal(false)} onCreate={async (input) => { const objective = await onCreateObjective(input); addObjective(objective); return objective; }} />
    <RubricCreateModal visible={rubricModal} onClose={() => setRubricModal(false)} onCreate={async (input) => { const rubric = await onCreateRubric(input); update({ rubric_id: rubric.id }); return rubric; }} />
  </View>;
}

function ObjectiveRow({ objective, alignment, lesson, onTarget, onRemove }: { objective: Pick<LearningObjective, 'id' | 'code' | 'title' | 'success_criteria'>; alignment: ObjectiveAlignmentField; lesson: LessonDetail; onTarget: (id: number | null) => void; onRemove: () => void }) {
  const targets = useMemo(() => [{ id: null, label: 'Whole lesson' }, ...lesson.content_blocks.filter((block) => ['video', 'recording', 'exercise', 'code_challenge'].includes(block.block_type)).map((block) => {
    const type = ['video', 'recording'].includes(block.block_type) ? 'Video' : 'Exercise';
    return { id: block.id, label: `${type} ${block.position}${block.title ? ` · ${block.title}` : ''}` };
  })], [lesson.content_blocks]);
  return <View style={styles.objective}><View style={styles.objectiveHeader}><View style={styles.code}><Text style={styles.codeText}>{objective.code}</Text></View><Text style={styles.objectiveTitle}>{objective.title}</Text><Pressable accessibilityRole="button" accessibilityLabel={`Remove objective ${objective.code}`} onPress={onRemove} style={styles.iconButton}><X color={palette.muted} size={17} /></Pressable></View><Text style={styles.criteria}>{objective.success_criteria}</Text><Text style={styles.targetLabel}>APPLIES TO</Text><View style={styles.targetChoices}>{targets.map((target) => <Pressable key={target.id || 'lesson'} accessibilityRole="radio" accessibilityLabel={target.label} accessibilityState={{ checked: alignment.content_block_id === target.id }} onPress={() => onTarget(target.id)} style={[styles.targetChoice, alignment.content_block_id === target.id && styles.targetChoiceActive]}><Text style={[styles.targetChoiceText, alignment.content_block_id === target.id && styles.targetChoiceTextActive]}>{target.label}</Text></Pressable>)}</View></View>;
}

function CheckFields({ check, objectives, locked, onChange }: { check: RetrievalCheckEditorFields; objectives: LearningObjective[]; locked: boolean; onChange: (patch: Partial<RetrievalCheckEditorFields>) => void }) {
  const setOption = (index: number, value: string) => onChange({ options: check.options.map((option, optionIndex) => optionIndex === index ? value : option) });
  const removeOption = (index: number) => onChange({ options: check.options.filter((_, optionIndex) => optionIndex !== index), correct_option: check.correct_option === index ? 0 : check.correct_option > index ? check.correct_option - 1 : check.correct_option });
  return <View style={styles.checkFields}>
    <Field label="CHECK TITLE"><TextInput accessibilityLabel="Quick check title" editable={!locked} value={check.title} onChangeText={(title) => onChange({ title })} placeholder="Quick check" placeholderTextColor={palette.quiet} style={[styles.input, locked && styles.disabled]} /></Field>
    <Field label="QUESTION"><TextInput accessibilityLabel="Quick check question" editable={!locked} multiline textAlignVertical="top" value={check.prompt} onChangeText={(prompt) => onChange({ prompt })} placeholder="Which command prints the current folder?" placeholderTextColor={palette.quiet} style={[styles.input, styles.multiline, locked && styles.disabled]} /></Field>
    <Field label="ALIGNED OBJECTIVE"><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}><ChoiceChip label="None" selected={check.learning_objective_id === null} disabled={locked} onPress={() => onChange({ learning_objective_id: null })} />{objectives.filter((objective) => objective.active).map((objective) => <ChoiceChip key={objective.id} label={objective.code} selected={check.learning_objective_id === objective.id} disabled={locked} onPress={() => onChange({ learning_objective_id: objective.id })} />)}</ScrollView></Field>
    <Field label="CHOICES · TAP THE CORRECT ANSWER"><View style={styles.options}>{check.options.map((option, index) => <View key={index} style={styles.optionRow}><Pressable accessibilityRole="radio" accessibilityLabel={`Mark choice ${index + 1} correct`} accessibilityState={{ checked: check.correct_option === index }} disabled={locked} onPress={() => onChange({ correct_option: index })} style={[styles.radio, check.correct_option === index && styles.radioActive]}><Text style={[styles.radioText, check.correct_option === index && styles.radioTextActive]}>{String.fromCharCode(65 + index)}</Text></Pressable><TextInput accessibilityLabel={`Quick check choice ${index + 1}`} editable={!locked} value={option} onChangeText={(value) => setOption(index, value)} placeholder={`Choice ${index + 1}`} placeholderTextColor={palette.quiet} style={[styles.optionInput, locked && styles.disabled]} /><Pressable accessibilityRole="button" accessibilityLabel={`Remove quick check choice ${index + 1}`} disabled={locked || check.options.length <= 2} onPress={() => removeOption(index)} style={[styles.iconButton, (locked || check.options.length <= 2) && styles.disabled]}><Trash2 color={palette.muted} size={16} /></Pressable></View>)}</View>{check.options.length < 6 && <Pressable accessibilityRole="button" accessibilityLabel="Add quick check choice" disabled={locked} onPress={() => onChange({ options: [...check.options, ''] })} style={styles.addChoice}><Plus color={palette.rubySoft} size={16} /><Text style={styles.secondaryText}>Add choice</Text></Pressable>}</Field>
    <Field label="EXPLANATION AFTER ANSWERING"><TextInput accessibilityLabel="Quick check explanation" editable={!locked} multiline textAlignVertical="top" value={check.explanation} onChangeText={(explanation) => onChange({ explanation })} placeholder="Explain why the answer is correct and what to remember." placeholderTextColor={palette.quiet} style={[styles.input, styles.multiline, locked && styles.disabled]} /></Field>
  </View>;
}

function ObjectiveCreateModal({ visible, onClose, onCreate }: { visible: boolean; onClose: () => void; onCreate: (input: { code: string; title: string; description?: string; success_criteria: string }) => Promise<LearningObjective> }) {
  const [code, setCode] = useState(''); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [criteria, setCriteria] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const reset = () => { setCode(''); setTitle(''); setDescription(''); setCriteria(''); setError(''); };
  const submit = async () => { if (!code.trim() || !title.trim() || !criteria.trim()) { setError('Code, title, and success criteria are required.'); return; } setSaving(true); setError(''); try { await onCreate({ code: code.trim(), title: title.trim(), description: description.trim() || undefined, success_criteria: criteria.trim() }); onClose(); } catch (requestError) { setError((requestError as Error).message || 'The objective could not be created.'); } finally { setSaving(false); } };
  return <CreateSheet visible={visible} title="New objective" subtitle="Create once, then reuse across lessons." saving={saving} error={error} onShow={reset} onClose={onClose} onSave={() => void submit()} saveLabel="Create objective"><Field label="CODE"><TextInput accessibilityLabel="Objective code" autoCapitalize="characters" value={code} onChangeText={setCode} placeholder="CSS.4" placeholderTextColor={palette.quiet} style={styles.input} /></Field><Field label="TITLE"><TextInput accessibilityLabel="Objective title" value={title} onChangeText={setTitle} placeholder="Build responsive layouts" placeholderTextColor={palette.quiet} style={styles.input} /></Field><Field label="DESCRIPTION · OPTIONAL"><TextInput accessibilityLabel="Objective description" value={description} onChangeText={setDescription} placeholder="A concise description for staff and students" placeholderTextColor={palette.quiet} style={styles.input} /></Field><Field label="SUCCESS CRITERIA"><TextInput accessibilityLabel="Objective success criteria" multiline textAlignVertical="top" value={criteria} onChangeText={setCriteria} placeholder="I can…" placeholderTextColor={palette.quiet} style={[styles.input, styles.multiline]} /></Field></CreateSheet>;
}

function RubricCreateModal({ visible, onClose, onCreate }: { visible: boolean; onClose: () => void; onCreate: (input: { title: string; description?: string; criteria: { title: string; description: string }[] }) => Promise<Rubric> }) {
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [criteria, setCriteria] = useState([{ title: '', description: '' }, { title: '', description: '' }]); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const reset = () => { setTitle(''); setDescription(''); setCriteria([{ title: '', description: '' }, { title: '', description: '' }]); setError(''); };
  const submit = async () => { const complete = criteria.map((criterion) => ({ title: criterion.title.trim(), description: criterion.description.trim() })).filter((criterion) => criterion.title || criterion.description); if (!title.trim() || !complete.length || complete.some((criterion) => !criterion.title || !criterion.description)) { setError('Add a title and complete every rubric criterion.'); return; } setSaving(true); setError(''); try { await onCreate({ title: title.trim(), description: description.trim() || undefined, criteria: complete }); onClose(); } catch (requestError) { setError((requestError as Error).message || 'The rubric could not be created.'); } finally { setSaving(false); } };
  return <CreateSheet visible={visible} title="New rubric" subtitle="Students see these criteria before submitting." saving={saving} error={error} onShow={reset} onClose={onClose} onSave={() => void submit()} saveLabel="Create rubric"><Field label="TITLE"><TextInput accessibilityLabel="Rubric title" value={title} onChangeText={setTitle} placeholder="Project quality" placeholderTextColor={palette.quiet} style={styles.input} /></Field><Field label="PURPOSE · OPTIONAL"><TextInput accessibilityLabel="Rubric description" value={description} onChangeText={setDescription} placeholder="What this rubric evaluates" placeholderTextColor={palette.quiet} style={styles.input} /></Field><Field label="CRITERIA"><View style={styles.criteriaList}>{criteria.map((criterion, index) => <View key={index} style={styles.criterionDraft}><TextInput accessibilityLabel={`Rubric criterion ${index + 1} title`} value={criterion.title} onChangeText={(value) => setCriteria((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, title: value } : item))} placeholder="Criterion title" placeholderTextColor={palette.quiet} style={styles.input} /><TextInput accessibilityLabel={`Rubric criterion ${index + 1} description`} multiline value={criterion.description} onChangeText={(value) => setCriteria((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, description: value } : item))} placeholder="What meeting this criterion looks like" placeholderTextColor={palette.quiet} style={[styles.input, styles.multiline]} /><Pressable accessibilityRole="button" accessibilityLabel={`Remove rubric criterion ${index + 1}`} disabled={criteria.length === 1} onPress={() => setCriteria((current) => current.filter((_, itemIndex) => itemIndex !== index))} style={[styles.removeCriterion, criteria.length === 1 && styles.disabled]}><Trash2 color={palette.muted} size={16} /><Text style={styles.removeText}>Remove criterion</Text></Pressable></View>)}</View><Pressable accessibilityRole="button" accessibilityLabel="Add rubric criterion" onPress={() => setCriteria((current) => [...current, { title: '', description: '' }])} style={styles.addChoice}><Plus color={palette.rubySoft} size={16} /><Text style={styles.secondaryText}>Add criterion</Text></Pressable></Field></CreateSheet>;
}

function CreateSheet({ visible, title, subtitle, saving, error, onShow, onClose, onSave, saveLabel, children }: { visible: boolean; title: string; subtitle: string; saving: boolean; error: string; onShow: () => void; onClose: () => void; onSave: () => void; saveLabel: string; children: React.ReactNode }) {
  return <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onShow={onShow} onRequestClose={() => { if (!saving) onClose(); }}><SafeAreaView style={styles.sheet}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.sheet}><View style={styles.sheetHeader}><Pressable accessibilityRole="button" accessibilityLabel="Close" disabled={saving} onPress={onClose} style={styles.sheetButton}><X color={palette.muted} size={20} /></Pressable><View style={styles.flex}><Text style={styles.sheetTitle}>{title}</Text><Text style={styles.sheetSubtitle}>{subtitle}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={saveLabel} disabled={saving} onPress={onSave} style={[styles.save, saving && styles.disabled]}><Text style={styles.saveText}>{saving ? 'Creating' : 'Create'}</Text></Pressable></View><ScrollView automaticallyAdjustKeyboardInsets keyboardShouldPersistTaps="handled" contentContainerStyle={styles.sheetContent}>{error ? <View accessibilityRole="alert" style={styles.error}><AlertCircle color={palette.rubySoft} size={18} /><Text style={styles.errorCopy}>{error}</Text></View> : null}{children}</ScrollView></KeyboardAvoidingView></SafeAreaView></Modal>;
}

function DesignCard({ icon, title, copy, children }: { icon: React.ReactNode; title: string; copy: string; children: React.ReactNode }) { return <View style={styles.card}><View style={styles.cardHeader}>{icon}<View style={styles.flex}><Text style={styles.cardTitle}>{title}</Text><Text style={styles.cardCopy}>{copy}</Text></View></View><View style={styles.cardBody}>{children}</View></View>; }
function ChoiceChip({ label, selected, disabled, onPress }: { label: string; selected: boolean; disabled?: boolean; onPress: () => void }) { return <Pressable accessibilityRole="radio" accessibilityState={{ checked: selected, disabled }} disabled={disabled} onPress={onPress} style={[styles.chip, selected && styles.chipActive, disabled && styles.disabled]}><Text style={[styles.chipText, selected && styles.chipTextActive]}>{label}</Text></Pressable>; }
function RubricSummary({ rubric }: { rubric?: Rubric | null }) { if (!rubric) return <Text style={styles.empty}>The selected rubric will appear after the library refreshes.</Text>; return <View style={styles.rubric}><Text style={styles.rubricTitle}>{rubric.title}</Text>{rubric.description && <Text style={styles.rubricDescription}>{rubric.description}</Text>}{rubric.criteria.map((criterion) => <View key={criterion.id} style={styles.rubricCriterion}><Check color={palette.success} size={14} /><View style={styles.flex}><Text style={styles.rubricCriterionTitle}>{criterion.title}</Text><Text style={styles.rubricCriterionCopy}>{criterion.description}</Text></View></View>)}</View>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text>{children}</View>; }

const styles = StyleSheet.create({
  section: { borderRadius: 21, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.panelRaised, padding: 16, gap: 13 }, eyebrow: { color: palette.rubySoft, fontFamily: fonts.bold, fontSize: 11, letterSpacing: 1 }, sectionTitle: { color: palette.text, fontFamily: fonts.extraBold, fontSize: 19 }, sectionCopy: { color: palette.muted, fontFamily: fonts.regular, fontSize: 12, lineHeight: 18, marginBottom: 4 }, flex: { flex: 1, minWidth: 0 }, muted: { color: palette.muted, fontFamily: fonts.regular, fontSize: 11 }, empty: { color: palette.muted, fontFamily: fonts.regular, fontSize: 11, lineHeight: 17 }, disabled: { opacity: 0.42 },
  card: { borderRadius: 18, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.panel, padding: 14 }, cardHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 9 }, cardTitle: { color: palette.text, fontFamily: fonts.bold, fontSize: 14 }, cardCopy: { color: palette.muted, fontFamily: fonts.regular, fontSize: 11, lineHeight: 17, marginTop: 3 }, cardBody: { gap: 11, marginTop: 14 },
  objective: { borderRadius: 15, borderWidth: 1, borderColor: '#4D2630', backgroundColor: '#211319', padding: 12 }, objectiveHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 }, objectiveTitle: { flex: 1, color: palette.text, fontFamily: fonts.bold, fontSize: 12 }, code: { borderRadius: 9, backgroundColor: '#351821', paddingHorizontal: 7, paddingVertical: 4 }, codeText: { color: palette.rubySoft, fontFamily: 'Menlo', fontSize: 11 }, criteria: { color: palette.muted, fontFamily: fonts.regular, fontSize: 11, lineHeight: 16, marginTop: 8 }, targetLabel: { color: palette.subtle, fontFamily: fonts.bold, fontSize: 11, letterSpacing: 0.7, marginTop: 10 }, targetChoices: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 6 }, targetChoice: { maxWidth: '100%', minHeight: 44, borderRadius: 12, borderWidth: 1, borderColor: palette.line, paddingHorizontal: 10, alignItems: 'center', justifyContent: 'center' }, targetChoiceActive: { borderColor: palette.ruby, backgroundColor: '#351821' }, targetChoiceText: { flexShrink: 1, color: palette.muted, fontFamily: fonts.bold, fontSize: 11, textAlign: 'center' }, targetChoiceTextActive: { color: palette.rubySoft }, iconButton: { width: 44, height: 44, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  library: { gap: 7 }, libraryLabel: { color: palette.subtle, fontFamily: fonts.bold, fontSize: 11, letterSpacing: 0.8 }, libraryChoice: { minHeight: 52, borderRadius: 14, borderWidth: 1, borderColor: palette.line, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 8 }, libraryChoiceText: { flex: 1, color: palette.text, fontFamily: fonts.semibold, fontSize: 11, lineHeight: 16 }, secondary: { minHeight: 44, borderRadius: 13, borderWidth: 1, borderColor: '#4D2630', paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, secondaryText: { color: palette.rubySoft, fontFamily: fonts.bold, fontSize: 11 }, chips: { gap: 7 }, chip: { minHeight: 44, borderRadius: 14, borderWidth: 1, borderColor: palette.line, paddingHorizontal: 13, alignItems: 'center', justifyContent: 'center' }, chipActive: { borderColor: palette.ruby, backgroundColor: '#351821' }, chipText: { color: palette.muted, fontFamily: fonts.bold, fontSize: 11 }, chipTextActive: { color: palette.rubySoft },
  rubric: { borderRadius: 15, backgroundColor: '#15271E', padding: 12 }, rubricTitle: { color: palette.success, fontFamily: fonts.bold, fontSize: 13 }, rubricDescription: { color: palette.muted, fontFamily: fonts.regular, fontSize: 11, lineHeight: 16, marginTop: 4 }, rubricCriterion: { flexDirection: 'row', alignItems: 'flex-start', gap: 7, marginTop: 10 }, rubricCriterionTitle: { color: palette.text, fontFamily: fonts.bold, fontSize: 11 }, rubricCriterionCopy: { color: palette.muted, fontFamily: fonts.regular, fontSize: 11, lineHeight: 16, marginTop: 2 },
  toggle: { minHeight: 72, borderRadius: 15, borderWidth: 1, borderColor: palette.line, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 10 }, toggleTitle: { color: palette.text, fontFamily: fonts.bold, fontSize: 12 }, toggleCopy: { color: palette.muted, fontFamily: fonts.regular, fontSize: 11, lineHeight: 16, marginTop: 3 }, locked: { borderRadius: 14, backgroundColor: '#282013', padding: 11, flexDirection: 'row', alignItems: 'flex-start', gap: 8 }, lockedText: { flex: 1, color: palette.warning, fontFamily: fonts.medium, fontSize: 11, lineHeight: 16 }, checkFields: { gap: 13 }, field: { gap: 7 }, label: { color: palette.subtle, fontFamily: fonts.bold, fontSize: 11, letterSpacing: 0.7 }, input: { minHeight: 48, borderRadius: 14, borderWidth: 1, borderColor: palette.line, backgroundColor: '#0A0C11', color: palette.text, fontFamily: fonts.regular, fontSize: 12, paddingHorizontal: 12, paddingVertical: 11 }, multiline: { minHeight: 90, lineHeight: 18 }, options: { gap: 7 }, optionRow: { flexDirection: 'row', alignItems: 'center', gap: 7 }, radio: { width: 44, height: 44, borderRadius: 13, borderWidth: 1, borderColor: palette.line, alignItems: 'center', justifyContent: 'center' }, radioActive: { borderColor: palette.success, backgroundColor: '#15271E' }, radioText: { color: palette.muted, fontFamily: fonts.bold, fontSize: 11 }, radioTextActive: { color: palette.success }, optionInput: { flex: 1, minHeight: 44, borderRadius: 13, borderWidth: 1, borderColor: palette.line, backgroundColor: '#0A0C11', color: palette.text, paddingHorizontal: 11, fontFamily: fonts.regular, fontSize: 12 }, addChoice: { alignSelf: 'flex-start', minHeight: 44, borderRadius: 13, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 6 },
  error: { borderRadius: 15, borderWidth: 1, borderColor: '#5D2830', backgroundColor: '#2B171B', padding: 11, flexDirection: 'row', alignItems: 'center', gap: 8 }, errorTitle: { color: palette.rubySoft, fontFamily: fonts.bold, fontSize: 12 }, errorCopy: { flex: 1, color: palette.muted, fontFamily: fonts.regular, fontSize: 11, lineHeight: 16 }, retry: { minHeight: 44, borderRadius: 13, borderWidth: 1, borderColor: '#5D2830', paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 5 }, retryText: { color: palette.rubySoft, fontFamily: fonts.bold, fontSize: 11 },
  sheet: { flex: 1, backgroundColor: palette.ink }, sheetHeader: { minHeight: 70, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.line, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 8 }, sheetButton: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, sheetTitle: { color: palette.text, fontFamily: fonts.bold, fontSize: 15 }, sheetSubtitle: { color: palette.muted, fontFamily: fonts.regular, fontSize: 11, marginTop: 3 }, save: { minHeight: 44, borderRadius: 14, backgroundColor: palette.ruby, paddingHorizontal: 13, alignItems: 'center', justifyContent: 'center' }, saveText: { color: palette.text, fontFamily: fonts.bold, fontSize: 11 }, sheetContent: { padding: 18, paddingBottom: 70, gap: 16 }, criteriaList: { gap: 10 }, criterionDraft: { borderRadius: 16, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.panel, padding: 10, gap: 8 }, removeCriterion: { alignSelf: 'flex-start', minHeight: 44, paddingHorizontal: 8, flexDirection: 'row', alignItems: 'center', gap: 6 }, removeText: { color: palette.muted, fontFamily: fonts.bold, fontSize: 11 },
});
